# cannot be run separately, method and experiment config need to be specified
seed: 4
model: NN
time_limit: 300
# hydra:
#   sweeper:
#     params:
#       seed: 0, 1, 2, 3, 4
# model: Linear, NN, FAMS, DNF, GerryFair
